#+title: Dotemacs
#+PROPERTY: header-args:emacs-lisp :tangle ~/.emacs :mkdirp yes

* Dotemacs
** Package setup

This bootstraps [[https://github.com/radian-software/straight.el][straight.el]] and [[https://github.com/jwiegley/use-package][use-package]] to install packages either from a package repository or from Github. I got the setup from [[https://jeffkreeftmeijer.com/emacs-straight-use-package/][here]], mostly.

#+begin_src emacs-lisp
  (setq package-enable-at-startup nil)
  (defvar bootstrap-version)
  (let ((bootstrap-file (expand-file-name "straight/repos/straight.el/bootstrap.el"
					  user-emacs-directory))
	(bootstrap-version 6))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer (url-retrieve-synchronously
			    "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el" 'silent 'inhibit-cookies)
  (goto-char (point-max))
  (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

  (straight-use-package 'use-package)
  (require 'use-package)

  (use-package
      straight
      :custom (straight-use-package-by-default t))
#+end_src

** Literate config setup

This enables using this org-mode file to generate a =.emacs= config file.

#+begin_src emacs-lisp
  (org-babel-do-load-languages 'org-babel-load-languages '((emacs-lisp . t)
							   (python . t)))

  (push '("conf-unix" . conf-unix) org-src-lang-modes)

  ;; Automatically tangle our Emacs.org config file when we save it
  (defun efs/org-babel-tangle-config ()
    (when (string-equal (buffer-file-name)
			(expand-file-name "~/Code/dotfiles/emacs/dotemacs.org"))
      ;; Dynamic scoping to the rescue
      (let ((org-confirm-babel-evaluate nil))
	(org-babel-tangle))))

  (add-hook 'org-mode-hook (lambda ()
			     (add-hook 'after-save-hook #'efs/org-babel-tangle-config)))
  (add-hook 'after-save-hook (lambda ()
			       (load-file (expand-file-name "~/.emacs"))))
#+end_src

** Git config

#+begin_src emacs-lisp
  (use-package magit)
  (use-package ghub)
  (use-package git-gutter
    :hook (prog-mode . git-gutter-mode)
    :config
    (setq git-gutter:update-interval 0.02))

  (use-package git-gutter-fringe
    :config
    (define-fringe-bitmap 'git-gutter-fr:added [224] nil nil '(center repeated))
    (define-fringe-bitmap 'git-gutter-fr:modified [224] nil nil '(center repeated))
    (define-fringe-bitmap 'git-gutter-fr:deleted [128 192 224 240] nil nil 'bottom))
#+end_src

** LISP/REPL config

#+begin_src emacs-lisp
  (use-package cider
      :ensure t)

  (use-package smartparens
    :config
    (setq sp-show-pair-from-inside nil)
    (require 'smartparens-config)
    (smartparens-global-mode 1)
    )

  (use-package clojure-mode
    :ensure t)
  
  (add-hook 'clojure-mode-hook #'smartparens-strict-mode)
  (add-hook 'org-mode-hook #'smartparens-strict-mode)
#+end_src

** Code formatting

*** Elisp

#+begin_src emacs-lisp
  (use-package elisp-format)
#+end_src

** Web mode

#+begin_src emacs-lisp
  (use-package web-mode :ensure t)
  (add-to-list 'auto-mode-alist '("\\.njk\\'" . web-mode))
#+end_src

** Org

#+begin_src emacs-lisp
  (setq org-agenda-files '("~/org"))

  (setq org-capture-templates
	      '(("t" "Todo" entry (file+headline "~/org/gtd.org" "Tasks")
		 "* TODO %?\n  %i\n  %a")
		  ("j" "Journal" entry (file+datetree "~/org/journal.org")
			  "* %?\nEntered on %U\n  %i\n  %a\n")
		  ("p" "Programming notes" entry (file+datetree "~/org/programming.org")
			  "* %?\nEntered on %U\n  %i\n  %a\n")))
    (global-set-key (kbd "C-c l") #'org-store-link)
    (global-set-key (kbd "C-c a") #'org-agenda)
    (global-set-key (kbd "C-c c") #'org-capture)
#+end_src

** Evil 🤘

I've been a vim guy for, like, 15 years at this point. It's hard enough switching over here,
but giving up modal editing and the shortcuts that are a part of me by now is just too much.
That's where evil comes in. In addition to installing evil-mode, we're adding a couple elisp
ports of vim plugins I can't live without as well as evil-collection which makes evil mode
play nicely with different kinds of buffers besides just text editing (magit, org, errors, &c.).

#+begin_src emacs-lisp
  (use-package
    evil
    :init
    (setq evil-want-keybinding nil)
    :config
    (evil-mode 1))

  (use-package
    evil-commentary
    :ensure t
    :config 
    (evil-commentary-mode 1))

  (use-package
    evil-surround
    :config (global-evil-surround-mode 1))

  (use-package
    evil-collection
    :after evil
    :config
    (evil-collection-init))
#+end_src

** 🍎 Compatibility

#+begin_src emacs-lisp
  (use-package
    simpleclip)
  (simpleclip-mode 1)

  ;; Make cmd-v work to paste from system clipboard
  ;; https://github.com/rolandwalker/simpleclip/issues/1
  (setq mac-option-modifier 'meta)
  (setq mac-command-modifier 'super)
  (setq mac-pass-command-to-system nil)
#+end_src

** UI & Theme

TODO Get ligatures working

Turn off most UI chrome.

#+begin_src emacs-lisp
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  (add-hook 'prog-mode-hook 'display-line-numbers-mode)
#+end_src

#+begin_src emacs-lisp
  (set-frame-font "JuliaMono 14" nil t)

  (use-package
    doom-themes
    :config
    ;; Global settings (defaults)
    (setq doom-themes-enable-bold t ; if nil, bold is universally disabled
    doom-themes-enable-italic t) ; if nil, italics is universally disabled
    (load-theme 'doom-one t)

    ;; Enable flashing mode-line on errors
    (doom-themes-visual-bell-config)
    ;; Corrects (and improves) org-mode's native fontification.
    (doom-themes-org-config))

  (use-package
    doom-modeline
    :init (doom-modeline-mode 1))

  (use-package all-the-icons)
#+end_src

*** Org Mode Appearance

Org mode needs some extra attention to really shine. This adds fancy bullets.

#+begin_src emacs-lisp
  ;; wrap lines depending on window size
  (add-hook 'org-mode-hook 'visual-line-mode) 
#+end_src

Also set custom faces and line heights for different levels of indentation. These settings are from [[https://zzamboni.org/post/beautifying-org-mode-in-emacs/][here]] but will probably change.

#+begin_src emacs-lisp
  (use-package org-modern)
  (global-org-modern-mode)
#+end_src
